package com.fagose.booklet.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookLike generated by hbm2java
 */
@Entity
@Table(name = "BookLike", catalog = "booklet")
public class BookLike implements java.io.Serializable {

	private Long bookLikeId;
	private Long bookLikerId;
	private Long bookId;
	private Date bookLikeDate;

	public BookLike() {
	}

	public BookLike(Long bookLikerId, Long bookId, Date bookLikeDate) {
		this.bookLikerId = bookLikerId;
		this.bookId = bookId;
		this.bookLikeDate = bookLikeDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BookLikeID", unique = true, nullable = false)
	public Long getBookLikeId() {
		return this.bookLikeId;
	}

	public void setBookLikeId(Long bookLikeId) {
		this.bookLikeId = bookLikeId;
	}

	@Column(name = "BookLikerID")
	public Long getBookLikerId() {
		return this.bookLikerId;
	}

	public void setBookLikerId(Long bookLikerId) {
		this.bookLikerId = bookLikerId;
	}

	@Column(name = "BookID")
	public Long getBookId() {
		return this.bookId;
	}

	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BookLikeDate", length = 19)
	public Date getBookLikeDate() {
		return this.bookLikeDate;
	}

	public void setBookLikeDate(Date bookLikeDate) {
		this.bookLikeDate = bookLikeDate;
	}

}
