package com.fagose.booklet.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Book", catalog = "booklet")
public class Book implements java.io.Serializable {

	private Integer bookId;
	private String name;
	private String description;
	private Integer adderId;
	private String writer;
	private String coverPhoto;

	public Book() {
	}

	public Book(String name, String description, Integer adderId,
			String writer, String coverPhoto) {
		this.name = name;
		this.description = description;
		this.adderId = adderId;
		this.writer = writer;
		this.coverPhoto = coverPhoto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BookID", unique = true, nullable = false)
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@Column(name = "Name", length = 450)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "AdderID")
	public Integer getAdderId() {
		return this.adderId;
	}

	public void setAdderId(Integer adderId) {
		this.adderId = adderId;
	}

	@Column(name = "Writer", length = 450)
	public String getWriter() {
		return this.writer;
	}

	public void setWriter(String writer) {
		this.writer = writer;
	}

	@Column(name = "CoverPhoto", length = 450)
	public String getCoverPhoto() {
		return this.coverPhoto;
	}

	public void setCoverPhoto(String coverPhoto) {
		this.coverPhoto = coverPhoto;
	}

}
