package com.fagose.booklet.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;s
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "Action", catalog = "booklet")
public class Action implements java.io.Serializable {

	private int actionSeqId;
	private Integer userId;
	private Integer actionId;

	public Action() {
	}

	public Action(int actionSeqId) {
		this.actionSeqId = actionSeqId;
	}

	public Action(int actionSeqId, Integer userId, Integer actionId) {
		this.actionSeqId = actionSeqId;
		this.userId = userId;
		this.actionId = actionId;
	}

	@Id
	@Column(name = "ActionSeqID", unique = true, nullable = false)
	public int getActionSeqId() {
		return this.actionSeqId;
	}

	public void setActionSeqId(int actionSeqId) {
		this.actionSeqId = actionSeqId;
	}

	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "ActionID")
	public Integer getActionId() {
		return this.actionId;
	}

	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

}
