package com.fagose.booklet.model;



/**
 * ActionTypes generated by hbm2java
 */
public enum ActionType{
	ADD_BOOK(0),
	ADD_COMMENT(1),
	ADD_BOOKLIKE(2),
	FOLLOW(3),
	UNFOLLOW(4),
	REGISTER(5);
	
	private int actionTypeCode;
	 
	private ActionType(int actionTypeCode) {
		this.actionTypeCode = actionTypeCode;
	}
 
	public int asCode() {
		return this.actionTypeCode;
	}
	public static ActionType getAction(int actionTypeCode){
		ActionType type = null;
		for(ActionType actionType : ActionType.values()){
			if(actionType.asCode()== actionTypeCode){
				type=actionType;
				break;
			}
		}
		return type;
	}
}