package com.fagose.booklet.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FollowShip generated by hbm2java
 */
@Entity
@Table(name = "FollowShip", catalog = "booklet")
public class FollowShip implements java.io.Serializable {

	private FollowShipId id;

	public FollowShip() {
	}

	public FollowShip(FollowShipId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "followerUserId", column = @Column(name = "FollowerUserID", nullable = false)),
			@AttributeOverride(name = "followedUserId", column = @Column(name = "FollowedUserID")),
			@AttributeOverride(name = "creationDate", column = @Column(name = "CreationDate", length = 19)) })
	public FollowShipId getId() {
		return this.id;
	}

	public void setId(FollowShipId id) {
		this.id = id;
	}

}
