package com.fagose.booklet.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hashtag generated by hbm2java
 */
@Entity
@Table(name = "Hashtag", catalog = "booklet")
public class Hashtag implements java.io.Serializable {

	private Integer hashTagId;
	private Integer bookId;
	private String tag;
	private Integer bookAdderId;
	private int bookBookId;

	public Hashtag() {
	}

	public Hashtag(int bookBookId) {
		this.bookBookId = bookBookId;
	}

	public Hashtag(Integer bookId, String tag, Integer bookAdderId,
			int bookBookId) {
		this.bookId = bookId;
		this.tag = tag;
		this.bookAdderId = bookAdderId;
		this.bookBookId = bookBookId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hashTagID", unique = true, nullable = false)
	public Integer getHashTagId() {
		return this.hashTagId;
	}

	public void setHashTagId(Integer hashTagId) {
		this.hashTagId = hashTagId;
	}

	@Column(name = "bookID")
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@Column(name = "tag", length = 1000)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "bookAdderID")
	public Integer getBookAdderId() {
		return this.bookAdderId;
	}

	public void setBookAdderId(Integer bookAdderId) {
		this.bookAdderId = bookAdderId;
	}

	@Column(name = "Book_BookID", nullable = false)
	public int getBookBookId() {
		return this.bookBookId;
	}

	public void setBookBookId(int bookBookId) {
		this.bookBookId = bookBookId;
	}

}
