package com.fagose.booklet.model;
// default package
// Generated Jan 13, 2014 10:33:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hashtag generated by hbm2java
 */
@Entity
@Table(name = "Hashtag", catalog = "booklet")
public class Hashtag implements java.io.Serializable {

	private Long hashTagId;
	private Long bookId;
	private String tag;

	public Hashtag() {
	}

	public Hashtag(Long bookId) {
		this.bookId = bookId;
	}

	public Hashtag(Long bookId, String tag) {
		this.bookId = bookId;
		this.tag = tag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hashTagID", unique = true, nullable = false)
	public Long getHashTagId() {
		return this.hashTagId;
	}

	public void setHashTagId(Long hashTagId) {
		this.hashTagId = hashTagId;
	}

	@Column(name = "bookID")
	public Long  getBookId() {
		return this.bookId;
	}

	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}

	@Column(name = "tag", length = 1000)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}
}
